---
- name: Include Vaulted Variables
  ansible.builtin.include_vars: "vault.yml"

- name: Include OS family variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Set Splunk Forwarder Download url
  ansible.builtin.set_fact:
    splunk_forwarder_url: "https://download.splunk.com/products/universalforwarder/releases/{{ splunk_forwarder_version }}/{{ splunk_forwarder_platform }}/{{ splunk_forwarder_filename }}"

- name: Debian | Install Splunk Forwarder
  ansible.builtin.apt:
    deb: "{{ splunk_forwarder_url }}"
    state: present
  when:
    - ansible_os_family == "Debian"

- name: Red Hat | Install Splunk Forwarder
  ansible.builtin.yum:
    name: "{{ splunk_forwarder_url }}"
    state: present
    disable_gpg_check: true
  when:
    - ansible_os_family == "RedHat"

- name: Create Symlink for Splunk
  ansible.builtin.file:
    path: /usr/bin/splunk
    src: /opt/splunkforwarder/bin/splunk
    state: link
    force: true

- name: Start the Splunk Forwarder for the first time
  ansible.builtin.command: /opt/splunkforwarder/bin/splunk start --accept-license --answer-yes --no-prompt --seed-passwd {{ splunk_forwarder_admin_password }}

- name: Wait for Splunk to start
  ansible.builtin.pause:
    seconds: 30

- name: Stop the Splunk Forwarder
  ansible.builtin.command: /opt/splunkforwarder/bin/splunk stop

- name: Set the Splunk Forwarder to start on boot
  ansible.builtin.command: /opt/splunkforwarder/bin/splunk enable boot-start

- name: Restart Splunk Forwarder
  ansible.builtin.systemd:
    name: SplunkForwarder
    state: restarted
    daemon_reload: true
    enabled: true

- name: Set the Splunk Forwarder Deployment-server
  ansible.builtin.command: /opt/splunkforwarder/bin/splunk set deploy-poll {{ splunk_forwarder_deployment_server }} -auth {{ splunk_forwarder_admin_user }}:{{ splunk_forwarder_admin_password }}
